### ISSUE TITLE
Add content to "about" page

### ISSUE THREAD

**Issue by JahBrewski** [Sozogo/sozogo#2]
About Us: Opens to 'What is SozoGo?' and "What does it mean' tab. Can also choose "Meet Our Team" or "Non-profit Status" or "Open Sourced Website" The Vision is it's own tab on the side, with each title below it marking a sub tab to the Vision.

What is SozoGo?

SozoGo is a website that seeks to unite the Church in love and action by giving you the opportunity to volunteer and make the difference you know you were made for. Churches and Christian organizations can make a profile and post volunteering events. Volunteers can then find these events and discover where they would like to serve, searching by their own personal interests, skills, and other criteria. Anyone and everyone can join for free and volunteer today! Plus, earn rewards and badges for volunteering!

What does it mean?

Sozo in Greek can be translated in three ways primarily: "saved, healed, or delivered." Part of the vision behind SozoGo is to see those who have been saved, healed, and/or delivered GOING out and helping to save, heal, and deliver others as well. So let's go! SozoGo.

How does SozoGo work?

It's simple! Create a profile, find a project that needs your help, volunteer, change the world.

Who can volunteer?

There are opportunities for everyone, young and old, non-Christians and Christians, men and women. All you have to do is sign up and we do the heavy lifting. We will match you with possible opportunities that fit your skills and interests. As a bonus, you can receive rewards for becoming part of our team of volunteers. Will you join us in our efforts to better our world through partnership with your unique abilities and sign up today?

Need Volunteers?

When we allow ourselves to work side by side with others who harbor different skills, we become more powerful than we could ever be alone. Together, we can be the essential components that form a brighter and better future. Sign your Church or Christian entity up to reap the benefits of effective workers who can help bring your biggest ideas to reality.

Meet Our Team 

Luke Simpson
President, CEO
LukeOSimpson@gmail.com
314-825-8376
 - Luke graduated from Wheaton College in 2013 with a bachelor’s degree in Biblical and Theological Studies in addition to minors in Economics and Spanish.  President and CEO of this nonprofit corporation, he seeks to use his love of God, mixed liberal arts education and unique experience to benefit the world through stirring the Church towards evangelism, unity, and love in action.

Joel Brewer 
VP, CTO
JoelBrewer01@gmail.com
314-753-7260
- Joel graduated from Wheaton College in the Spring of 2013 with a degree in Biology. While in school, he served as a Web Developer and Video Editor for Bastian Voice Institute, utilizing technology to develop creative solutions for increasing productivity and creating a multimedia-rich educational website. He is now the Owner and Lead Web Application Developer for Brewer Digital, collaborating directly with clients to develop exceptional websites/web-applications. As CTO of SozoGo, Joel is the responsible for the creation, development, and upkeep of the wonderful website you are now using :). You're welcome.

Tanya Brewer
TanyaBrewer01@gmail.com
 - Tanya graduated from Wheaton College with a bachelor's degree in Nursing and is currently working towards getting her Master's degree from Vanderbilt as a Pediatric Nurse Practitioner. Tanya's skills are obviously diverse, and here at SozoGo she is at work behind the scenes in multiple ways, including working with Social Media and helping with the creation of SozoGo. In addition to her love of serving others, she always has enough love left over for her wonderful cats and would certainly love to introduce you to them!

Matthew Simpson 
MatthewSimpson718@gmail.com
- Matthew is currently a student at the Missouri University of Science and Technology studying to become a Mechanical Engineer. He has been an integral part in the initial stage of creation and development of SozoGo, serves on the board, and works on the Social Media Marketing of SozoGo. Always filled with a desire to help, he is a good fit here with SozoGo. He is also an avid lover of bears, wolves, and country music. 

Non-Profit Status

SozoGo is an official 501(c)(3) organization and is funded primarily by donations. This means we depend on people like you to help us keep running in order to continue to change the world! It also means your donations are tax-deductible! Donate today! 
*link*

Open-Sourced Website

SozoGo is an open-sourced website, allowing everyone to contribute to the development of SozoGo's overall purpose of matching people with volunteer opportunities in order to change the world. It's basically a website for volunteers, that is also built by volunteers! If you know anything about website design you can find our project at www.github.com/SozoGo/SozoGo and make your mark on SozoGo. So what are you waiting for!
*Document: 7 Reasons to Get Involved with Github*

The Vision:

Acts 2

In Acts 2, we catch a glimpse of the early Church. Immediately when the disciples received the Holy Spirit, things change. There is this strange reversal of the Tower of Babel, where instead of everyone being unable to communicate, people from various nations are able to hear the disciples declaring the wonders of God in their own tongues. Peter preaches about what just happened (Pentecost) and about the cross and their numbers increased 3000 people (and kept increasing daily). We also see in this chapter that the church had “everything in common,” and I do not doubt this included skills as well as material belongings. This here in Acts 2 is the beginning of a new era, the Church era. It is creating a beautiful picture of both evangelism and unity that transformed the world that seems to be lost amongst many churches and people today. 

The Church

What I hope for this website to be is a way to return to that early Church we see in the book of Acts. Where people see and hear the wonders of God, in their own tongues, in loving actions, in their own communities. I plan on seeing miracles done far beyond simple good works by Spirit-filled Christians in the moments of encounter this site will create. Let’s make it easy for Christians to be Christians and participate in “good works which God planned beforehand that we should walk in them.” Let’s provide them opportunities for encounter in order to evangelize to a generation that so desperately needs Jesus. Let’s create an environment where Christians can begin to understand what it means to live within a community of believers, both in their church and the Church (Big C).

Workers for the Harvest

Statistics show that 80% of Americans call themselves Christians. If this is the case, why do things seem to be in such shambles? If 4/5 people in the USA were serving others, do you think that things would look the same? We’ve got a chance to change a people, a nation, and the world, by helping Christians to act Christianly. There’s always work for the Church to do, let’s try to assure that there are enough workers, for the harvest is plentiful and according to statistics there are certainly enough “Christians.” Let’s let the world know who we are and allow Christians to actively and constantly serve Christ and His Church. Let’s allow the world to know who we Christians are by our love in action.

Social Media Making a Real-World Impact 

Many worry about our children, teens, and even adults becoming lost in a world of technology, drifting in cyberspace. It has become normal to obsess over social media pages like Facebook, Twitter, and Instagram. But none of it is real. Stalking someone’s Facebook is a completely different experience than meeting them in person. Just because you read J. Bieb’s tweets doesn’t mean you know him. But what if social media made real-world change? This is what I hope to see, where social media simply becomes a platform from which to spring into action in the real world and make a difference.

Evangelists making evangelists

The creation of this network would also allow churches across the world to evangelize in a coordinated effort. What would it look like if all the Christians in the world were serving in church events at their church and other's churches? It would be a constant effort to create opportunities to serve and evangelize for those who may be too timid or unsure of how they can evangelize. A single evangelist can only do so much. But if that evangelist creates more evangelists, it is an exponential growth that could overwhelm and consume the world. I hope that this network may unite the Church, stir evangelism, bring love through service, and bring many into the loving embrace of Christ both now and in the age to come.

Reconciliation

In addition to all this, the website will create amazing opportunities for reconciliation. I pray it will bring social reconciliation as people of different economic backgrounds serve each other and alongside one another in areas they may not have visited otherwise. I pray that it will create racial reconciliation, as events allow peoples of all different races and ethnicities to encounter each other in new and transformative ways, including allowing hushed voices to be heard. I pray that it will bring reconciliation amongst denominations as they begin to realize that we are serving the same Jesus, and work with the power of the same Spirit. But most importantly, I pray that it would bring reconciliation with God, as people begin to discover where God has already been working, as they begin to see God working inside themselves and other ambassadors of Christ, and as they encounter the love of God for the very first time through one act of kindness.

Who Might Be Interested In Using SozoGo?

Who might be interested in using it? Maybe someone who is bored, wondering what they can do. Maybe looking for a new and interesting idea for a date. Maybe someone who is extremely lonely, with no ideas where to look for friends. Maybe Christians, wanting to step up and get a chance to help others. Maybe non-Christians, longing to do the same. Maybe older or jobless folks who still desire to make a difference and gain experience. Maybe professional men and women, like doctors, lawyers, those in business, who vowed they would bless others with their skills. Maybe an evangelist who longs for the chance to meet new people to share the love of Christ with, both those they are serving and those with whom they serve. Maybe someone just out of college, trying to gain experience. Maybe a high school student trying to fulfill their community service hours. Maybe a large church with a large event that they would like to make even bigger. Maybe a smaller church who could use more people to do more and become more than themselves. Maybe a pastor. Maybe a sinner. Maybe you.

Additional verses:
	In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.
-whoever refreshes others will be refreshed. (Proverbs 11:25)
	-“Faith without works is dead” (James 2:17) 
	-“Here I am, send me.” (Isaiah 6:8) 
	-But prove yourselves doers of the word, and not merely hearers who delude themselves (James 1:22) 
	-Isaiah 61…all of it
	-What you have done for the least of these you have done for me. (Matthew 25:40) 
	-Religion that God our Father accepts as pure and faultless is this: to look after orphans and widows in their distress and to keep oneself from being polluted by the world. (James 1:27) 
	-Do not be overcome by evil but overcome evil with good (Romans 12:21) 
	-I remain confident of this: I will see the goodness of the Lord in the land of the living.
	-Make my joy complete by being of one Spirit (Philippians 2:2) 
	-Bear each others burdens and in this way fulfill the law of Christ (Galatians 6:2) 
	-For so is the will of God, that by well-doing ye should put to silence the ignorance of foolish men (1 Peter 2:15) 
	-Acts 2…all of it 
	-We remember before our God and Father your work produced by faith, your labor prompted by love, and your endurance inspired by hope in our Lord Jesus Christ. (1 Thessalonians 1:3) 
	-Just as a body, though one, has many parts, but all its many parts form one body, so it is with Christ. (1 Corinthians 12:12) 
	-Many more…

**Comment by losimpson** [comment]
@JahBrewski @tlbrew  I added information for all of us in the  "Meet our Team" section above in order to keep moving forward. Feel free to read through and edit/delete as you please.
