### ISSUE TITLE
MVP Minor Issues

### ISSUE THREAD

**Issue by losimpson** [Sozogo/sozogo#28]
- "We are Sozogo" at top needs to have G capitalized

-please create block somewhere on home page with simplification of how SozoGo works: "Create profile -> Find a project that needs your help -> Volunteer -> Change the World"

-creating organization - "press control" hint for multiple select common events or change this also into "tags"

-address only asks for city not state or zip

-deletes short description, common events selected, and website if statement of beliefs not accepted upon creation of church. pastor option also disappeared (not sure this can be fixed)

-Proceeds to say Welcome to sozogo! at top. Capitalize S and G.

-creating project - project attributes and related professions listed twice

-creation of project - did not allow for different address than the church/organization to be entered. Did not allow entry of any project specific contact information

-Created project - does not show any information regarding church that created it, nor associated project focuses/professions, special instructions. (perhaps you just have only created the "search/display" calendar and not fuller version upon selection yet)

-creation of volunteer - does not request state or zip for volunteer. professions are listed twice. May also want to consider putting nonprofit/church profession into selections. does not ask "fun questions" 

-failling to confirm password while creating volunteer deletes languages and interests

-welcome to sozogo! again after creating volunteer profile needs S and G capitalized

-projects page - no ability to select "attending", no "meter" to say how many volunteer spots available or if project is full

**Comment by JahBrewski** [comment]
Started working on these this evening @losimpson -- got about halfway through. This week is crazy hectic for Tanya and I (we're moving to Dallas), but I'll work to get the rest of these items knocked out ASAP.

**Comment by losimpson** [comment]
Alrighty, thanks @jahbrewski . Blessings on the move!

**Comment by JahBrewski** [comment]
Alright, did a bit more. Fixed the duplicate project attributes/related professions when creating a projects/volunteers!

**Comment by JahBrewski** [comment]
@losimpson Just added the ability for users to "attend" events, along with a "meter" to keep track of progress. I think that should complete most of the items on this list. Want to click through everything and make sure things are working for you?

**Comment by losimpson** [comment]
@JahBrewski great! everything worked! I did think of one other thing, though. It looks like now that we can select to attend the event, we'll need to limit the ability to select attending to volunteers only and not organizations too (since organizations can't actually attend an event). If that's an easy enough fix I think we can go ahead and close this issue and then it'll be up to your discretion for when to launch
