### ISSUE TITLE
Add ability to accept donations through site

### ISSUE THREAD

**Issue by JahBrewski** [Sozogo/sozogo#3]

**Comment by losimpson** [comment]
Make notes on donation page if possible:

Donations are tax-deductible.

If you do not wish to donate online, cash and checks can be sent to:
SozoGo
471 Magna Carta
Saint Louis, MO 63141

This organization may accept contributions of: real property; closely held securities; intellectual property such as patents, trademarks, and copyrights; works of music or art; licenses; royalties; automobiles, boats, planes, or other vehicles; or collectibles of any type if said contributions further the purposes of this organization. This organization will not accept donations if any conditions imposed by the donor on the contribution limit this organization’s ability to achieve its purposes or force this organization to conduct activities that are not in furtherance of 501(c)(3) purposes. We will ensure that donations are accepted in accordance with 501(c)(3) regulations and we will properly determine fair market value according to Publication 561. We will not actively solicit such contributions.
 If you wish to make a donation in one of these forms please contact us: 314-825-8376

**Comment by JahBrewski** [comment]
Added verbiage + paypal button
