### ISSUE TITLE
Create Staging Site

### ISSUE THREAD

**Issue by losimpson** [Sozogo/sozogo#35]
Would be nice to have staging site for Jim to do end user testing, allowing people to do things like post fake events.

**Comment by losimpson** [comment]
@JahBrewski tryin to prioritize things. how much work would this entail? if it is much more than copy and paste code it can delay, but if it's that simple might as well knock it out quick.

**Comment by JahBrewski** [comment]
@losimpson: Shouldn't be too hard! Just a couple commands on the command line I believe! This will also be helpful to test new features, etc.
